### ISSUE TITLE
Trim of Cuisine display occasionally causes results to not appear to be consistent with search (although are, just not displayed)

### ISSUE THREAD

**Issue by mandyjmiller** [uberponky/Food-Finder#47]
Shall we just gloss over this?!

![image](https://github.com/uberponky/Food-Finder/assets/151660136/e2dc059b-ca97-4775-a90b-34613cee3ebb)

**Comment by uberponky** [comment]
Yeah I thought this might happen. One solution would be to simply add the searched for cuisine to the top of the array. The array sanitisation removes duplicates, so it shouldn't show twice in the event it IS in the sanitised list.

**Comment by mandyjmiller** [comment]
I'm just going to kill this. It's working, just not necessarilt displaying all cuisines in tidied list
