### ISSUE TITLE
Update Petro Canada on main page

### ISSUE THREAD

**Issue by mandyjmiller** [uberponky/Food-Finder#61]
![image](https://github.com/uberponky/Food-Finder/assets/151660136/794fbade-4549-4346-b897-cb12f8183ae5)

Turns out this  fancy restaurant is a grocery store chain at a petrol station. Can you please just update to something a bite more creative! These are just placeholders (hard coded) on the index.html page.

**Comment by khumbulani9** [comment]
I have made updates to the restaurant Petro-Canada, as this was later on identified as a petrol station. The new chosen restaurant is known as Vero Gusto.
